-- begin NLQC_QC_COURSE
create unique index IDX_NLQC_QC_COURSE_UNIQ_QC_COURSE_NO on NLQC_QC_COURSE (QC_COURSE_NO) ^
-- end NLQC_QC_COURSE
-- begin NLQC_MATERIAL
create unique index IDX_NLQC_MATERIAL_UNIQ_MATERIAL_NO on NLQC_MATERIAL (MATERIAL_NO) ^
create unique index IDX_NLQC_MATERIAL_UNIQ_MATERIAL_NAME on NLQC_MATERIAL (MATERIAL_NAME) ^
-- end NLQC_MATERIAL
-- begin NLQC_DEVICE
alter table NLQC_DEVICE add constraint FK_NLQC_DEVICE_ON_WORK_STATION foreign key (WORK_STATION_ID) references NLQC_WORK_STATION(ID)^
create unique index IDX_NLQC_DEVICE_UNIQ_DEVICE_NO on NLQC_DEVICE (DEVICE_NO) ^
create index IDX_NLQC_DEVICE_ON_WORK_STATION on NLQC_DEVICE (WORK_STATION_ID)^
-- end NLQC_DEVICE

-- begin NLQC_CAR_MODEL
create unique index IDX_NLQC_CAR_MODEL_UNIQ_CAR_MODEL_NO on NLQC_CAR_MODEL (CAR_MODEL_NO) ^
-- end NLQC_CAR_MODEL
-- begin NLQC_QC_ITEM
alter table NLQC_QC_ITEM add constraint FK_NLQC_QC_ITEM_ON_QC_ARGS foreign key (QC_ARGS_ID) references NLQC_QC_ARGS(ID)^
alter table NLQC_QC_ITEM add constraint FK_NLQC_QC_ITEM_ON_DEVICE foreign key (DEVICE_ID) references NLQC_DEVICE(ID)^
alter table NLQC_QC_ITEM add constraint FK_NLQC_QC_ITEM_ON_MATEIAL foreign key (MATEIAL_ID) references NLQC_MATERIAL(ID)^
alter table NLQC_QC_ITEM add constraint FK_NLQC_QC_ITEM_ON_FIRST_QC_FREQUENCY foreign key (FIRST_QC_FREQUENCY_ID) references NLQC_FREQUENCY(ID)^
alter table NLQC_QC_ITEM add constraint FK_NLQC_QC_ITEM_ON_INITIATIVE_QC_FREQUENCY foreign key (INITIATIVE_QC_FREQUENCY_ID) references NLQC_FREQUENCY(ID)^
alter table NLQC_QC_ITEM add constraint FK_NLQC_QC_ITEM_ON_FINALLY_QC_FREQUENCY foreign key (FINALLY_QC_FREQUENCY_ID) references NLQC_FREQUENCY(ID)^
alter table NLQC_QC_ITEM add constraint FK_NLQC_QC_ITEM_ON_ROUNDS_QC_FREQUENCY foreign key (ROUNDS_QC_FREQUENCY_ID) references NLQC_FREQUENCY(ID)^
alter table NLQC_QC_ITEM add constraint FK_NLQC_QC_ITEM_ON_QC_FLOW foreign key (QC_FLOW_ID) references NLQC_QC_FLOW(ID)^
create index IDX_NLQC_QC_ITEM_ON_QC_ARGS on NLQC_QC_ITEM (QC_ARGS_ID)^
create index IDX_NLQC_QC_ITEM_ON_DEVICE on NLQC_QC_ITEM (DEVICE_ID)^
create index IDX_NLQC_QC_ITEM_ON_MATEIAL on NLQC_QC_ITEM (MATEIAL_ID)^
create index IDX_NLQC_QC_ITEM_ON_FIRST_QC_FREQUENCY on NLQC_QC_ITEM (FIRST_QC_FREQUENCY_ID)^
create index IDX_NLQC_QC_ITEM_ON_INITIATIVE_QC_FREQUENCY on NLQC_QC_ITEM (INITIATIVE_QC_FREQUENCY_ID)^
create index IDX_NLQC_QC_ITEM_ON_FINALLY_QC_FREQUENCY on NLQC_QC_ITEM (FINALLY_QC_FREQUENCY_ID)^
create index IDX_NLQC_QC_ITEM_ON_ROUNDS_QC_FREQUENCY on NLQC_QC_ITEM (ROUNDS_QC_FREQUENCY_ID)^
create index IDX_NLQC_QC_ITEM_ON_QC_FLOW on NLQC_QC_ITEM (QC_FLOW_ID)^
-- end NLQC_QC_ITEM
-- begin NLQC_QC_FLOW
alter table NLQC_QC_FLOW add constraint FK_NLQC_QC_FLOW_ON_CAR_MODEL foreign key (CAR_MODEL_ID) references NLQC_CAR_MODEL(ID)^
alter table NLQC_QC_FLOW add constraint FK_NLQC_QC_FLOW_ON_QC_COURSE foreign key (QC_COURSE_ID) references NLQC_QC_COURSE(ID)^
alter table NLQC_QC_FLOW add constraint FK_NLQC_QC_FLOW_ON_WORK_STATION foreign key (WORK_STATION_ID) references NLQC_WORK_STATION(ID)^
create index IDX_NLQC_QC_FLOW_ON_CAR_MODEL on NLQC_QC_FLOW (CAR_MODEL_ID)^
create index IDX_NLQC_QC_FLOW_ON_QC_COURSE on NLQC_QC_FLOW (QC_COURSE_ID)^
create index IDX_NLQC_QC_FLOW_ON_WORK_STATION on NLQC_QC_FLOW (WORK_STATION_ID)^
-- end NLQC_QC_FLOW
-- begin NLQC_FREQUENCY
alter table NLQC_FREQUENCY add constraint FK_NLQC_FREQUENCY_ON_UNIT foreign key (UNIT_ID) references NLQC_UNIT_FOR_FREQUENCY(ID)^
create index IDX_NLQC_FREQUENCY_ON_UNIT on NLQC_FREQUENCY (UNIT_ID)^
-- end NLQC_FREQUENCY
-- begin NLQC_WORK_STATION_DEVICE_LINK
alter table NLQC_WORK_STATION_DEVICE_LINK add constraint FK_WORSTADEV_ON_WORK_STATION foreign key (WORK_STATION_ID) references NLQC_WORK_STATION(ID)^
alter table NLQC_WORK_STATION_DEVICE_LINK add constraint FK_WORSTADEV_ON_DEVICE foreign key (DEVICE_ID) references NLQC_DEVICE(ID)^
-- end NLQC_WORK_STATION_DEVICE_LINK
-- begin NLQC_WORK_STATION_QC_ARGS_LINK
alter table NLQC_WORK_STATION_QC_ARGS_LINK add constraint FK_WORSTAQCARG_ON_QC_ARGS foreign key (QC_ARGS_ID) references NLQC_QC_ARGS(ID)^
alter table NLQC_WORK_STATION_QC_ARGS_LINK add constraint FK_WORSTAQCARG_ON_WORK_STATION foreign key (WORK_STATION_ID) references NLQC_WORK_STATION(ID)^
-- end NLQC_WORK_STATION_QC_ARGS_LINK
-- begin NLQC_QC_COURSE_WORK_STATION_LINK
alter table NLQC_QC_COURSE_WORK_STATION_LINK add constraint FK_QCCOUWORSTA_ON_QC_COURSE foreign key (QC_COURSE_ID) references NLQC_QC_COURSE(ID)^
alter table NLQC_QC_COURSE_WORK_STATION_LINK add constraint FK_QCCOUWORSTA_ON_WORK_STATION foreign key (WORK_STATION_ID) references NLQC_WORK_STATION(ID)^
-- end NLQC_QC_COURSE_WORK_STATION_LINK

-- begin NLQC_QC_RECORD_BILLS_ITEM
alter table NLQC_QC_RECORD_BILLS_ITEM add constraint FK_NLQC_QC_RECORD_BILLS_ITEM_ON_FIRST_HZ foreign key (FIRST_HZ_ID) references NLQC_FREQUENCY(ID)^
alter table NLQC_QC_RECORD_BILLS_ITEM add constraint FK_NLQC_QC_RECORD_BILLS_ITEM_ON_INITIATIVE_HZ foreign key (INITIATIVE_HZ_ID) references NLQC_FREQUENCY(ID)^
alter table NLQC_QC_RECORD_BILLS_ITEM add constraint FK_NLQC_QC_RECORD_BILLS_ITEM_ON_LAST_HZ foreign key (LAST_HZ_ID) references NLQC_FREQUENCY(ID)^
alter table NLQC_QC_RECORD_BILLS_ITEM add constraint FK_NLQC_QC_RECORD_BILLS_ITEM_ON_CIRCLE_HZ foreign key (CIRCLE_HZ_ID) references NLQC_FREQUENCY(ID)^
alter table NLQC_QC_RECORD_BILLS_ITEM add constraint FK_NLQC_QC_RECORD_BILLS_ITEM_ON_QC_RECORD_BILLS foreign key (QC_RECORD_BILLS_ID) references NLQC_QC_RECORD_BILLS(ID)^
create index IDX_NLQC_QC_RECORD_BILLS_ITEM_ON_FIRST_HZ on NLQC_QC_RECORD_BILLS_ITEM (FIRST_HZ_ID)^
create index IDX_NLQC_QC_RECORD_BILLS_ITEM_ON_INITIATIVE_HZ on NLQC_QC_RECORD_BILLS_ITEM (INITIATIVE_HZ_ID)^
create index IDX_NLQC_QC_RECORD_BILLS_ITEM_ON_LAST_HZ on NLQC_QC_RECORD_BILLS_ITEM (LAST_HZ_ID)^
create index IDX_NLQC_QC_RECORD_BILLS_ITEM_ON_CIRCLE_HZ on NLQC_QC_RECORD_BILLS_ITEM (CIRCLE_HZ_ID)^
create index IDX_NLQC_QC_RECORD_BILLS_ITEM_ON_QC_RECORD_BILLS on NLQC_QC_RECORD_BILLS_ITEM (QC_RECORD_BILLS_ID)^
-- end NLQC_QC_RECORD_BILLS_ITEM
