alter table NLQC_WORK_STATION add constraint FK_NLQC_WORK_STATION_ON_QC_COURSE foreign key (QC_COURSE_ID) references NLQC_QC_COURSE(ID);
create unique index IDX_NLQC_WORK_STATION_UNIQ_WORK_STATION_NO on NLQC_WORK_STATION (WORK_STATION_NO) ;
create index IDX_NLQC_WORK_STATION_ON_QC_COURSE on NLQC_WORK_STATION (QC_COURSE_ID);
