alter table NLQC_DEVICE add constraint FK_NLQC_DEVICE_ON_WORK_STATION foreign key (WORK_STATION_ID) references NLQC_WORK_STATION(ID);
create index IDX_NLQC_DEVICE_ON_WORK_STATION on NLQC_DEVICE (WORK_STATION_ID);
