create table NLQC_QC_RECORD_BILLS_ITEM (
    ID varchar(36) not null,
    VERSION integer not null,
    CREATE_TS timestamp,
    CREATED_BY varchar(50),
    UPDATE_TS timestamp,
    UPDATED_BY varchar(50),
    DELETE_TS timestamp,
    DELETED_BY varchar(50),
    --
    QC_RECORD_BILL_ITEM varchar(255),
    QC_ITEM_NO varchar(255),
    QC_ARGS_NO varchar(255),
    KEY_MATERIAL_NO varchar(255),
    ACTUAL_MATERIAL_NO varchar(255),
    QC_DEVICE_NO varchar(255),
    ACTUAL_DEVICE_NO varchar(255),
    NORM_VALUE bigint,
    UP_VALUE bigint,
    DOWN_VALUE bigint,
    ACTUAL_VALUE bigint,
    UNIT varchar(255),
    FIRST_HZ_ID varchar(36),
    INITIATIVE_HZ_ID varchar(36),
    LAST_HZ_ID varchar(36),
    CIRCLE_HZ_ID varchar(36),
    QC_TIME timestamp,
    IS_CONTROL boolean,
    QC_RESULT varchar(255),
    NOTE varchar(255),
    QC_RECORD_BILLS_ID varchar(36),
    --
    primary key (ID)
);