create table NLQC_QC_RECORD_ARCHIVE (
    ID varchar(36) not null,
    VERSION integer not null,
    CREATE_TS timestamp,
    CREATED_BY varchar(50),
    UPDATE_TS timestamp,
    UPDATED_BY varchar(50),
    DELETE_TS timestamp,
    DELETED_BY varchar(50),
    --
    QC_RECORD_BILL_ITEM varchar(255),
    CREATE_TIME timestamp,
    CAR_MODEL_NO varchar(255),
    QC_WORK_STATION_NO varchar(255),
    QC_WORK_STATION_NAME varchar(255),
    QC_ARGS_NO varchar(255),
    QC_ARGS_TYPE varchar(255),
    QC_TYPE varchar(255),
    QC_USER varchar(255),
    KEY_MATERIAL_NO varchar(255),
    ACTUAL_MATERIAL_NO varchar(255),
    QC_DEVICE_NO varchar(255),
    ACTUAL_DEVICE_NO varchar(255),
    NORM_VALUE bigint,
    UP_VALUE bigint,
    DOWN_VALUE bigint,
    ACTUAL_VALUE bigint,
    UNIT varchar(255),
    FIRST_HZ varchar(255),
    INITIATIVE_HZ varchar(255),
    LAST_HZ varchar(255),
    CIRCLE_HZ varchar(255),
    QC_TIME varchar(255),
    IS_CONTROL boolean,
    QC_RESULT varchar(255),
    ITEM_NOTE varchar(255),
    --
    primary key (ID)
);